services:
  laravel.test:
    build:
      context: './vendor/laravel/sail/runtimes/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: 'sail-8.4/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
      - mailpit

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
      MYSQL_USER: '${DB_USERNAME:-laraveluser}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80' # Access phpMyAdmin at http://localhost:8080
    environment:
      #   MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-root}'
      #   MYSQL_ROOT_HOST: '%'
      #   MYSQL_ALLOW_EMPTY_PASSWORD: 1
      #   MYSQL_DATABASE: '${MYSQL_DATABASE:-database}'
      #   MYSQL_USER: '${MYSQL_USER:-username}'
      #   MYSQL_PASSWORD: '${MYSQL_PASSWORD:-password}'
      #   PMA_HOST: '${PMA_HOST:-mysql}'
      #   PMA_PORT: '${PMA_PORT:-3306}'
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
      PMA_USER: '${DB_USERNAME:-laraveluser}'
      PMA_PASSWORD: '${DB_PASSWORD:-password}'
    depends_on:
      - mysql
    networks:
      - sail

networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
